Repository agentic-labs/lsproxy, pull requests merged in 2024-12, with the labels that each got.

#83 always use default exclude patterns in ts, and use default include patterns if none are found in tsconfig
  README.md
  lsproxy/Dockerfile
  lsproxy/src/lsp/languages/clang.rs
  lsproxy/src/lsp/languages/java.rs
  lsproxy/src/lsp/languages/typescript.rs
  lsproxy/src/lsp/manager.rs
  lsproxy/src/utils/file_utils.rs
Labels: size:XS

#84 Lazy didopen
  lsproxy/src/lsp/client.rs
  lsproxy/src/lsp/languages/clang.rs
  lsproxy/src/lsp/languages/java.rs
  lsproxy/src/lsp/languages/python.rs
  lsproxy/src/lsp/languages/rust.rs
  lsproxy/src/lsp/languages/typescript.rs
  lsproxy/src/lsp/manager.rs
  lsproxy/src/utils/file_utils.rs
  lsproxy/src/utils/workspace_documents.rs
  lsproxy/tests/java_test.rs
  lsproxy/tests/python_test.rs
Labels: size:L

#85 fix python
  lsproxy/Dockerfile
  release/Dockerfile
  release/install-lsproxy.sh
Labels: size:M

#86 disable syntax server in ts, only use full
  lsproxy/src/lsp/client.rs
  lsproxy/src/lsp/languages/clang.rs
  lsproxy/src/lsp/languages/rust.rs
  lsproxy/src/lsp/languages/typescript.rs
Labels: size:M

#88 Small fixes
  lsproxy/src/ast_grep/client.rs
  release/install-lsproxy.sh
Labels: size:XS

#93 Golang
  lsproxy/Dockerfile
  lsproxy/src/api_types.rs
  lsproxy/src/ast_grep/rules/go/function.yml
  lsproxy/src/ast_grep/rules/go/method.yml
  lsproxy/src/ast_grep/rules/go/type.yml
  lsproxy/src/lsp/languages/golang.rs
  lsproxy/src/lsp/languages/mod.rs
  lsproxy/src/lsp/manager.rs
  lsproxy/src/main.rs
  lsproxy/src/utils/file_utils.rs
  lsproxy/src/utils/workspace_documents.rs
  openapi.json
  release/Dockerfile
  sample_project/go/golang_astar/astar.go
  sample_project/go/golang_astar/grid.go
  sample_project/go/golang_astar/node.go
  sample_project/go/golang_astar/search.go
  sample_project/go/main.go
Labels: size:L

#91 feat: Add JWT middleware with token validation and environment secret
  .github/workflows/openapi-spec-check.yml
  .github/workflows/openapi-version-check.yml
  lsproxy/Cargo.toml
  lsproxy/Dockerfile
  lsproxy/scripts/process_monitor.sh
  lsproxy/src/lib.rs
  lsproxy/src/middleware/jwt.rs
  lsproxy/src/middleware/mod.rs
  lsproxy/src/middleware/tests.rs
  openapi.json
  performance/process_resource_csv.py
  scripts/generate_jwt.py
  scripts/run.sh
Labels: size:L

#95 fix go for e2b
  .github/workflows/image_upload.yml
  lsproxy/src/lsp/languages/golang.rs
  release/Dockerfile
  release/install-lsproxy.sh
Labels: size:S

#96 Add health check endpoint
  .github/workflows/image_upload.yml
  .gitignore
  lsproxy/Cargo.toml
  lsproxy/src/api_types.rs
  lsproxy/src/handlers/health.rs
  lsproxy/src/handlers/mod.rs
  lsproxy/src/lib.rs
  lsproxy/tests/java_test.rs
  lsproxy/tests/python_test.rs
  openapi.json
  release/install-lsproxy.sh
Labels: size:L

#100 Fix definition code context range
  lsproxy/src/handlers/find_definition.rs
Labels: size:S

#103 Better error handling
  lsproxy/src/handlers/find_definition.rs
  lsproxy/src/handlers/find_references.rs
  lsproxy/src/handlers/list_files.rs
  lsproxy/src/lsp/client.rs
  lsproxy/src/lsp/languages/clang.rs
  lsproxy/src/lsp/languages/golang.rs
  lsproxy/src/lsp/languages/java.rs
  lsproxy/src/lsp/languages/php.rs
  lsproxy/src/lsp/languages/rust.rs
  lsproxy/src/lsp/languages/typescript.rs
  lsproxy/src/lsp/process.rs
Labels: size:L
