Repository agentic-labs/lsproxy, pull requests merged in 2024-11, with the labels that each got.

#65 Switch to jedi, remove declaration option
  lsproxy/Dockerfile
  lsproxy/src/api_types.rs
  lsproxy/src/handlers/find_references.rs
  lsproxy/src/lsp/client.rs
  lsproxy/src/lsp/languages/python.rs
  lsproxy/src/lsp/manager.rs
  openapi.json
  release/Dockerfile
Labels: size:M

#63 Additional language servers: C, CPP
  .gitignore
  lsproxy/Dockerfile
  lsproxy/src/api_types.rs
  lsproxy/src/ast_grep/client.rs
  lsproxy/src/ast_grep/rules/c/class.yml
  lsproxy/src/ast_grep/rules/c/function.yml
  lsproxy/src/ast_grep/rules/c/type.yml
  lsproxy/src/ast_grep/rules/cpp/class.yml
  lsproxy/src/ast_grep/rules/cpp/function.yml
  lsproxy/src/ast_grep/rules/cpp/method.yml
  lsproxy/src/ast_grep/rules/cpp/type.yml
  lsproxy/src/ast_grep/rules/go/function.yml
  lsproxy/src/ast_grep/rules/go/method.yml
  lsproxy/src/ast_grep/rules/go/type.yml
  lsproxy/src/handlers/mod.rs
  lsproxy/src/handlers/read_source_code.rs
  lsproxy/src/lib.rs
  lsproxy/src/lsp/client.rs
  lsproxy/src/lsp/languages/clang.rs
  lsproxy/src/lsp/languages/mod.rs
  lsproxy/src/lsp/languages/python.rs
  lsproxy/src/lsp/manager.rs
  lsproxy/src/lsp/process.rs
  lsproxy/src/test_utils.rs
  lsproxy/src/utils/file_utils.rs
  lsproxy/src/utils/workspace_documents.rs
  openapi.json
  sample_project/c/main.c
  sample_project/c/map.c
  sample_project/c/map.h
  sample_project/c/pathfinding.c
  sample_project/c/pathfinding.h
Labels: size:XXL

#68 Handle empty definitions
  lsproxy/src/lsp/client.rs
Labels: size:XS

#67 java + tests
  .gitignore
  lsproxy/Dockerfile
  lsproxy/src/api_types.rs
  lsproxy/src/ast_grep/rules/java/class.yml
  lsproxy/src/ast_grep/rules/java/interface.yml
  lsproxy/src/ast_grep/rules/java/method.yml
  lsproxy/src/lsp/languages/java.rs
  lsproxy/src/lsp/languages/mod.rs
  lsproxy/src/lsp/languages/python.rs
  lsproxy/src/lsp/manager.rs
  lsproxy/src/test_utils.rs
  lsproxy/src/utils/workspace_documents.rs
  openapi.json
  release/Dockerfile
  sample_project/java/AStar.java
  sample_project/java/Main.java
  sample_project/java/Node.java
Labels: size:XL

#69 include decorators in function defs
  lsproxy/src/ast_grep/rules/python/function.yml
Labels: size:S

#72 Add python extensions and fix decorator bug
  lsproxy/src/ast_grep/rules/python/function.yml
  lsproxy/src/handlers/definitions_in_file.rs
  lsproxy/src/handlers/find_definition.rs
  lsproxy/src/handlers/find_references.rs
  lsproxy/src/lsp/languages/rust.rs
  lsproxy/src/lsp/manager.rs
  lsproxy/src/utils/workspace_documents.rs
  sample_project/python/graph.py
Labels: size:L

#73 pull code and range with metavar
  lsproxy/Dockerfile
  lsproxy/src/ast_grep/client.rs
  lsproxy/src/ast_grep/rules/c/class.yml
  lsproxy/src/ast_grep/rules/c/function.yml
  lsproxy/src/ast_grep/rules/c/type.yml
  lsproxy/src/ast_grep/rules/cpp/class.yml
  lsproxy/src/ast_grep/rules/cpp/function-declaration.yml
  lsproxy/src/ast_grep/rules/cpp/function-definition.yml
  lsproxy/src/ast_grep/rules/cpp/function.yml
  lsproxy/src/ast_grep/rules/cpp/method.yml
  lsproxy/src/ast_grep/rules/cpp/type.yml
  lsproxy/src/ast_grep/rules/go/type.yml
  lsproxy/src/ast_grep/rules/java/class.yml
  lsproxy/src/ast_grep/rules/java/interface.yml
  lsproxy/src/ast_grep/rules/java/method.yml
  lsproxy/src/ast_grep/rules/javascript/class.yml
  lsproxy/src/ast_grep/rules/javascript/function.yml
  lsproxy/src/ast_grep/rules/javascript/method.yml
  lsproxy/src/ast_grep/rules/javascript/variable.yml
  lsproxy/src/ast_grep/rules/python/class.yml
  lsproxy/src/ast_grep/rules/python/function.yml
  lsproxy/src/ast_grep/rules/python/variable.yml
  lsproxy/src/ast_grep/rules/rust/enum.yml
  lsproxy/src/ast_grep/rules/rust/function.yml
  lsproxy/src/ast_grep/rules/rust/implementation.yml
  lsproxy/src/ast_grep/rules/rust/struct.yml
  lsproxy/src/ast_grep/rules/rust/trait.yml
  lsproxy/src/ast_grep/rules/rust/type.yml
  lsproxy/src/ast_grep/rules/tsx/class.yml
  lsproxy/src/ast_grep/rules/tsx/function.yml
  lsproxy/src/ast_grep/rules/tsx/interface.yml
  lsproxy/src/ast_grep/rules/tsx/method.yml
  lsproxy/src/ast_grep/rules/tsx/variable.yml
  lsproxy/src/ast_grep/rules/typescript/class.yml
  lsproxy/src/ast_grep/rules/typescript/function.yml
  lsproxy/src/ast_grep/rules/typescript/interface.yml
  lsproxy/src/ast_grep/rules/typescript/method.yml
  lsproxy/src/ast_grep/rules/typescript/variable.yml
  lsproxy/src/ast_grep/sgconfig.yml
  lsproxy/src/ast_grep/test_sgconfig.yml
  lsproxy/src/ast_grep/types.rs
  lsproxy/src/handlers/definitions_in_file.rs
  lsproxy/src/handlers/find_definition.rs
  lsproxy/src/lsp/manager.rs
  lsproxy/src/test_utils.rs
  lsproxy/tests/java_test.rs
  lsproxy/tests/python_test.rs
  sample_project/python/graph.py
  sample_project/typescript/PathfinderDisplay.tsx
  sample_project/typescript/astar.ts
  sample_project/typescript/main.ts
  sample_project/typescript/node.ts
  sample_project/typescript/types.ts
  sample_project/typescript/visualization.ts
  scripts/test.sh
Labels: size:XXL

#80 Better compile commands generation
  lsproxy/Cargo.toml
  lsproxy/src/lsp/languages/clang.rs
  lsproxy/src/lsp/manager.rs
  lsproxy/src/utils/file_utils.rs
  lsproxy/src/utils/workspace_documents.rs
Labels: size:L

#81 install script
  .github/workflows/image_upload.yml
  lsproxy/Dockerfile
  lsproxy/src/lsp/languages/clang.rs
  release/Dockerfile
  release/install-lsproxy.sh
Labels: size:L
