Repository agentic-labs/lsproxy, pull requests merged in 2025-01, with the labels that each got.

#109 Check input positions against valid identifiers in the file. This is a breaking change
  lsproxy/src/api_types.rs
  lsproxy/src/ast_grep/client.rs
  lsproxy/src/ast_grep/rules/cpp/all-identifiers.yml
  lsproxy/src/ast_grep/rules/go/all-identifiers.yml
  lsproxy/src/ast_grep/rules/java/all-identifiers.yml
  lsproxy/src/ast_grep/rules/javascript/all-identifiers.yml
  lsproxy/src/ast_grep/rules/php/all-identifiers.yml
  lsproxy/src/ast_grep/rules/python/all-identifiers.yml
  lsproxy/src/ast_grep/rules/rust/all-identifiers.yml
  lsproxy/src/ast_grep/rules/tsx/all-identifiers.yml
  lsproxy/src/ast_grep/types.rs
  lsproxy/src/handlers/find_definition.rs
  lsproxy/src/handlers/find_references.rs
  lsproxy/src/handlers/mod.rs
  lsproxy/src/handlers/utils.rs
  lsproxy/src/lib.rs
  lsproxy/src/lsp/manager/manager.rs
  lsproxy/src/utils/file_utils.rs
  lsproxy/src/utils/workspace_documents.rs
  openapi.json
  repro.py
Labels: size:XL

#112 Endpoint for searching for identifiers in a file by name
  lsproxy/src/api_types.rs
  lsproxy/src/handlers/find_identifier.rs
  lsproxy/src/handlers/mod.rs
  lsproxy/src/lib.rs
  lsproxy/src/lsp/manager/manager.rs
  openapi.json
Labels: size:L

#111 Check input positions against valid identifiers in the file. This is a breaking change
  lsproxy/src/api_types.rs
  lsproxy/src/ast_grep/client.rs
  lsproxy/src/ast_grep/rules/cpp/all-identifiers.yml
  lsproxy/src/ast_grep/rules/go/all-identifiers.yml
  lsproxy/src/ast_grep/rules/java/all-identifiers.yml
  lsproxy/src/ast_grep/rules/javascript/all-identifiers.yml
  lsproxy/src/ast_grep/rules/php/all-identifiers.yml
  lsproxy/src/ast_grep/rules/python/all-identifiers.yml
  lsproxy/src/ast_grep/rules/rust/all-identifiers.yml
  lsproxy/src/ast_grep/rules/tsx/all-identifiers.yml
  lsproxy/src/ast_grep/types.rs
  lsproxy/src/handlers/find_definition.rs
  lsproxy/src/handlers/find_identifier.rs
  lsproxy/src/handlers/find_references.rs
  lsproxy/src/handlers/mod.rs
  lsproxy/src/handlers/utils.rs
  lsproxy/src/lib.rs
  lsproxy/src/lsp/manager/language_tests/c_tests.rs
  lsproxy/src/lsp/manager/manager.rs
  lsproxy/src/utils/file_utils.rs
  lsproxy/src/utils/workspace_documents.rs
  openapi.json
Labels: size:XL

#114 final changes
  lsproxy/Cargo.toml
  release/build-and-extract.sh
  release/install-lsproxy.sh
Labels: size:S

#115 Fix location checking
  lsproxy/src/ast_grep/client.rs
  lsproxy/src/ast_grep/types.rs
  lsproxy/src/lsp/manager/manager.rs
Labels: size:M

#116 Improve find referenced symbols
  lsproxy/Cargo.toml
  lsproxy/src/ast_grep/client.rs
  lsproxy/src/ast_grep/types.rs
  lsproxy/src/handlers/definitions_in_file.rs
  lsproxy/src/handlers/error.rs
  lsproxy/src/handlers/find_definition.rs
  lsproxy/src/handlers/find_identifier.rs
  lsproxy/src/handlers/find_referenced_symbols.rs
  lsproxy/src/handlers/find_references.rs
  lsproxy/src/handlers/health.rs
  lsproxy/src/handlers/list_files.rs
  lsproxy/src/handlers/mod.rs
  lsproxy/src/handlers/read_source_code.rs
  lsproxy/src/lib.rs
  lsproxy/src/lsp/manager/manager.rs
  lsproxy/src/utils/file_utils.rs
  release/install-lsproxy.sh
Labels: size:L

#117 Add ruby support
  lsproxy/Cargo.toml
  lsproxy/Dockerfile
  lsproxy/src/api_types.rs
  lsproxy/src/ast_grep/identifier/rules/ruby/all-identifiers.yml
  lsproxy/src/ast_grep/symbol/rules/ruby/class.yml
  lsproxy/src/ast_grep/symbol/rules/ruby/method.yml
  lsproxy/src/ast_grep/symbol/rules/ruby/module.yml
  lsproxy/src/handlers/find_referenced_symbols.rs
  lsproxy/src/handlers/find_references.rs
  lsproxy/src/lib.rs
  lsproxy/src/lsp/languages/mod.rs
  lsproxy/src/lsp/languages/ruby.rs
  lsproxy/src/lsp/manager/manager.rs
  lsproxy/src/test_utils.rs
  lsproxy/src/utils/file_utils.rs
  lsproxy/src/utils/workspace_documents.rs
  openapi.json
  release/Dockerfile
  release/install-lsproxy.sh
  sample_project/ruby/decorators.rb
  sample_project/ruby/graph.rb
  sample_project/ruby/main.rb
  sample_project/ruby/search.rb
Labels: size:XL

#119 Cross compile gopls
  lsproxy/Dockerfile
  release/Dockerfile
Labels: size:S
